### ISSUE TITLE
Deleting discussions

### ISSUE THREAD

**Issue by dillerk** [YodasMyDad/Dialogue#20]
You can not delete the last discussion in a category. I kept getting an error, created a second discussion/poll and then deleted the orignal just fine. I also then tried to delete the new discussion and it errored again.

**Comment by voskefox** [comment]
Maybe that's what i have, but when I am adding an extra discussion it will not delete, only when i add a quote i can delete a discussion of my own. If it's a discussion of another user it will give an error also.
This is what i am getting.




deleting dialogue posts

ad de Vos started this topic 27 minutes ago

Unsubscribe
 

Hi I installed dialogue 1.1 (forum package) on 7.1.4 . Al things working smooth, only when I want to delete a post i get this error :

[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +14634175
   System.Collections.ObjectModel.KeyedCollection`2.get_Item(TKey key) +70
   Dialogue.Logic.Services.MemberService.RefreshMemberPosts(Member member, Int32 amount) in c:\Users\gebruiker\Source\Repos\Dialogue\Src\Dialogue.Logic\Services\MemberService.cs:337
   Dialogue.Logic.Services.PostService.SyncMembersPostCount(List`1 members) in c:\Users\gebruiker\Source\Repos\Dialogue\Src\Dialogue.Logic\Services\PostService.cs:60
   Dialogue.Logic.Services.TopicService.Delete(Topic topic) in c:\Users\gebruiker\Source\Repos\Dialogue\Src\Dialogue.Logic\Services\TopicService.cs:488
   Dialogue.Logic.Controllers.DialoguePostSurfaceController.DeletePost(Guid id) in c:\Users\gebruiker\Source\Repos\Dialogue\Src\Dialogue.Logic\Controllers\DialoguePostController.cs:189
   lambda_method(Closure , ControllerBase , Object[] ) +173

**Comment by leen3o** [comment]
I'm still finishing up the next version of MVCForum. Once that's done, I'll have a look into this.

**Comment by voskefox** [comment]
Nice to hear Lee! Thank you in advance. I catched a fork of your solution but I do not get the solution running. Any tips?  If I can get it running I can debug it myself and give you some support.

**Comment by leen3o** [comment]
I can't help there I'm afraid. It should just run after you have restored the DB.

**Comment by voskefox** [comment]
Ok, no worries. I wil digg deeper into it.

Thanks so far!


Van: Lee [mailto:notifications@github.com]
Verzonden: donderdag 29 januari 2015 9:42
Aan: leen3o/Dialogue
CC: A.S.L. de Vos
Onderwerp: Re: [Dialogue] Deleting discussions (#20)


I can't help there I'm afraid. It should just run after you have restored the DB.

**Comment by YodasMyDad** [comment]
Fixed in v2.0
