### ISSUE TITLE
Error when adding empty Poll question

### ISSUE THREAD

**Issue by epernst** [YodasMyDad/Dialogue#28]
I tried to add  poll to a question. 
Adding the poll works semi-fine, I'm able to create a poll and add question. 
But if you add a question without a text in the question, then it fails with:
_Cannot insert the value NULL into column 'Answer', table 'Dialogue.dbo.DialoguePollAnswer';_ 
_column does not allow nulls. INSERT fails._
_The statement has been terminated._

If you add the poll (without an empty question), then it saves fine.

**Comment by YodasMyDad** [comment]
Fixed
