### ISSUE TITLE
Dialogue Umbraco Installation

### ISSUE THREAD

**Issue by crisleiria** [YodasMyDad/Dialogue#42]
I want to test the Forum integrattion om my Umbraco Website.
I am testing on my local installation and I have installed without any problems from Umbraco package Repository and follow all the steps recommended after installation (I think so...).
When I try to access from the FronEnd Website the Forum page I have this error:

The view '~/App_Plugins/Dialogue/Themes//Views/Dialogue.cshtml' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/App_Plugins/Dialogue/Themes//Views/Dialogue.cshtml

![image](https://cloud.githubusercontent.com/assets/9845290/5247396/e4832cac-7969-11e4-8431-7fff3ad9cef2.png)

What I am doing wrong?

Thanks in advance

**Comment by Dame1701** [comment]
Hi Guys,

The issue above with the double slash occurs if you don't set a theme for your forum. If you notice, the double slash is actually where the theme name would be inserted.

To fix this, go into the Umbraco back-end and in the Content tree click on your forum. Click on the tab Theme. I suspect you will see that nothjing is selected in the drop down. In the drop down select the theme you wish to use (probably default) and save changes.

Lee, would it be possible for you to display some sort of useful error message if the theme name is null or empty, maybe tell the user that they need to make a choice here, or better still maybe automatically select the default theme when they create a new forum?

Hope this helps a bit,

Cheers,

Damien

**Comment by sy8718** [comment]
Hi,

When I install dialogue, I got an error

![image](https://cloud.githubusercontent.com/assets/17307156/15600717/16514b3a-242f-11e6-8425-4dd4c3662cec.png)

any idea?

**Comment by number45** [comment]
crisleiria Did you ever find out how to do this?  We need to do something similar on our site.

> On my Umbraco site, I already add member registered (about 60 site
member) (before Dialogue installation) and I want all of them to use the
forum. The question here is that they are site member and not Dialogue
Member... So everything that I do on the forum with the site member have
some weird behavior (and I understand that). With Dialogue members errors
go away... (I had to change the language to en - us, it is important that
you mention that on the installation procedure)

> How can I transform site members on Dialogue members?

**Comment by crisleiria** [comment]
Hi,
this was a long time ago... We are not using Dialogue plugin anymore because of this problem and others small things.
But I remember that I have created a SQLProcedure for doing this at the time. Umbraco do not have any tool for doing this programatically.

If you have a website with already many members registered and want to integrate a forum, you have this problem with Dialogue. I have used Simpily Forums plugin instead [https://our.umbraco.org/projects/collaboration/simpily-forums/](url).
It is very (I mean very) simple forum comparing to Dialogue plugin, but it uses Umbraco default member types. And I have extended this plugin with features that I needed.

**Comment by number45** [comment]
Yeah it's looking like we'd need to do some modification to Dialogue to get it working without our existing members.  I'll have a look at that Simpily Forums and see if it does enough of what we need out the box.  It may be easier and quicker to just add that and forgo some of the more advanced forum features.

Thanks for the response.
