### ISSUE TITLE
Edit reply to post

### ISSUE THREAD

**Issue by untiedshoes** [YodasMyDad/Dialogue#48]
Hi,

It seems that when you've replied to a post, you're not able to edit it. The edit button and url are fine, but the edit form isn't rendered.

When you create a reply, the post is not set to IsTopicStarter, which needs to be true to be able to edit the post :(

You can edit the main post (if you created it), but you can't edit any replies to posts even if you're admin, or you created the replies.

Has anyone else had this issue?

**Comment by YodasMyDad** [comment]
Sorry I cannot replicate this, I can edit posts fine.
