### ISSUE TITLE
Problems installing dialogue, TableExistenceChecker exception

### ISSUE THREAD

**Issue by Dame1701** [YodasMyDad/Dialogue#49]
Hi,

I've been trying to install Dialogue in a fresh Umbraco 7 installation (7.2.5) but each time I try, the installation quits with the following error:

Could not load type 'System.Data.Entity.Infrastructure.TableExistenceChecker' from assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

[TypeLoadException: Could not load type 'System.Data.Entity.Infrastructure.TableExistenceChecker' from assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.]
   System.Data.Entity.SqlServerCompact.SqlCeProviderServices..ctor() +0
   System.Data.Entity.SqlServerCompact.SqlCeProviderServices..cctor() +28

[TypeInitializationException: The type initializer for 'System.Data.Entity.SqlServerCompact.SqlCeProviderServices' threw an exception.]

[TargetInvocationException: Exception has been thrown by the target of an invocation.]

All I can do to resolve this is to uninstall the entity framework using the package manager which then allows me to log back into umbraco and from there I can uninstall the package. 

It looks like some sort of exception is being thrown by the entity framework. I added the Sql Compact edition using Package manager: Install-Package EntityFramework.SqlServerCompact is this the correct one...?

Many thanks for your help,

Damien

**Comment by Dame1701** [comment]
Problem resolved. I had to downgrade the EntityFramework and EntityFramework.SqlServerCompact to v6.1.1 which got me back into Umbraco from where I was able to uninstall the partial installation of Dialogue and then reinstall. From what i can gather there are a few breaking changes between 6.1.1 and later (currently 6.1.3).

**Comment by rokinroj** [comment]
Oh man Dame1701 - thanks for that!!  I was banging my head on the desk for hours - using NuGet without specifying a version was getting me 6.1.3 and I was seeing all the same issues with Dialogue.  6.1.1 fixed me right up, thanks again :-)

**Comment by YodasMyDad** [comment]
Dialogue has been tested against SQL CE and you should not run a forum on SQL CE
