### ISSUE TITLE
The specified table does not exist. [ DialogueTopic ]

### ISSUE THREAD

**Issue by Prospero100** [YodasMyDad/Dialogue#52]
Hi There,

After installing, completing the installation, and then publishing the "Forum One" demo, I'm getting the error "The specified table does not exist. [ DialogueTopic ]" when I try browse to the forum page.

Any ideas how to debug this?

It's the dialogue.cshtml view which is thowing the error, presumably it is the controller though that is really throwing the error. How do I find the DialogueTopicSurfaceController?

Also - which part of the installation process should have created the table "DialogueTopic" ?
![applicationerror](https://cloud.githubusercontent.com/assets/13137296/8458484/51cd91d4-200f-11e5-8841-ef7b02f5d199.jpg)

**Comment by leen3o** [comment]
It's saying the tables are not there. So check to see in the DB if that table does indeed exist. Once installed, did you click the almost finished page button after the package installs.

**Comment by Prospero100** [comment]
Thanks Lee,
I the install process (via Nuget) didn't run smoothly. I was installing against a SQL CE database via Visual Studio & Nuget on my dev machine. I've seen in other posts that SQL CE isn't recommended. I had got past a missing reference errors - by installing entity framework packages. I ended up with missing table error after completing the install without errors and hitting the almost finished button.

I suspect that the whole install on my machine was corrupt, as I'd run it 3 or 4 times before getting to the almost finished button.

I've since installed on a fresh environment, this time against a SQL Azure instance. I'm not too sure if this is supported or not. I'm having a few issues with that too - these are posting/replying problems rather than installation. Is SQL Express the only database I can use? I can do this in development, but the production site is destined for hosting on Azure. Is this going to be a problem?

**Comment by leen3o** [comment]
Azure should be fine as along as all the tables and files are uploaded.

**Comment by Prospero100** [comment]
Thanks Lee,
I've tried to install against an Azure based umbraco, the installation fails with a message:

>No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SqlServerCe.4.0'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

Checking the web config of the site there was no entity framework section. I've tried adding an entityFramework config section in as follows:

![entityframeworkconfig](https://cloud.githubusercontent.com/assets/13137296/8520632/ef880e00-23d3-11e5-9658-1710d8860a71.jpg)

but I got the error message:
>The Entity Framework provider type 'System.Data.Entity.SqlServerCompact.SqlCeProviderServices, EntityFramework.SqlServerCompact' registered in the application config file for the ADO.NET provider with invariant name 'System.Data.SqlServerCe.4.0' could not be loaded. Make sure that the assembly-qualified name is used and that the assembly is available to the running application. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

So I checked the bin folder, and sure enough the EntityFramework.SqlServerCompact.dll is absent. The EntityFramework.SqlServer.dll is present though.

I'm unclear on what is using the SQLCE entity framework. Presumably it must be Dialogue as the error message only appears when I try to install the package (I don't get as far as the "almost finished button" and the whole umbraco installation is knocked over by the entityframework config error)

How do I get the SQLCE framework installed on the Azure web application?

I'm uncertain that I'm taking the right approach - I seem to be hitting too many errors to be on the right path, so I think my approach must be wrong. Can you advise me on the best approach to use - what do you do when creating development & production environments? Should I create a local Umbraco environment, install Dialogue and then try to promote that to azure once it is configured, or should I create an azure Umbraco environment and configure Dialogue on that directly. What are the pre-requisites required? 

I've tried both, but I seem to get different errors in each environment, but nowhere do I get an error free installation.

It would help me a lot if I could replicate the environment set up that you use.  Which Sql version, Umbraco version, IIS version/location do you use. 

I really want to get this working - it's just what I need, but I'm struggling with it.

Much appreciated,
Paul

**Comment by leen3o** [comment]
Hi Paul - This doesn't support SQL CE. Needs to be SQL Express or SQL Azure. It adds the correct Entity Framework Web.config in the second part of the installer.

https://github.com/leen3o/Dialogue/blob/master/Src/Dialogue.Logic/UserControls/DialogueInstaller.ascx.cs#L411
