### ISSUE TITLE
Unable to launch after change

### ISSUE THREAD

**Issue by Arextion** [YodasMyDad/Dialogue#57]
I got the forum up and running but didn't create any categories etc and wanted to change the Forum Name.. I think it was after that, that i stopped working with this error:
Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 2:  @model Dialogue.Logic.Models.ViewModels.ViewAdminSidePanelViewModel
Line 3:  @{
Line 4:      var logOutUrl = string.Format("{0}?{1}={1}", Dialogue.Logic.Dialogue.Settings().ForumRootUrl, AppConstants.LogOut);
Line 5:  }
Line 6:  

Any idea why?

**Comment by leen3o** [comment]
Make sure you have at least one Category, and republish it along with the child nodes. Look like it can't find the root node, so it's either unpublished or somewhere it doesn't understand.
