### ISSUE TITLE
Question about Dialogue Guest access

### ISSUE THREAD

**Issue by gcouttsconnect** [YodasMyDad/Dialogue#59]
Hi,

I'm trying out your Dialogue forum and had a question about the 'Guest' role. Does the terminology 'Guest' relate to a non-logged in person?

I've created a Poll within a Category and set the permission of the Dialogue Guest to allow to Vote in Polls. But within the DialoguePollSurfaceController/UpdatePoll the first condition checks the ServiceFactory.PollService.HasUserVotedAlready() method passing in the CurrentMember.Id as a parameter. As the user is a guest the CurrentMember call fails. 

Am I misinterpreting the terminology of 'Guest' here?

Many Thanks

Graeme

**Comment by YodasMyDad** [comment]
Yes, but guests cannot use the Polls with the current functionality. Guests are just general people browsing the forum.
