### ISSUE TITLE
Server error - cannot register admin user

### ISSUE THREAD

**Issue by shaisti** [YodasMyDad/Dialogue#64]
Dialogue being installed on umbraco 7.1.4

installation was successful but when i have tried to register a user i.e. first ever user, admin user, the registration page come up with error

Server Error in '/' Application.
Method not found: 'Umbraco.Core.Models.IPublishedContentProperty Umbraco.Core.Models.IPublishedContent.GetProperty(System.String)'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.MissingMethodException: Method not found: 'Umbraco.Core.Models.IPublishedContentProperty Umbraco.Core.Models.IPublishedContent.GetProperty(System.String)'.

Source Error:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:
[MissingMethodException: Method not found: 'Umbraco.Core.Models.IPublishedContentProperty Umbraco.Core.Models.IPublishedContent.GetProperty(System.String)'.]
   nForum.BusinessLogic.Models.Forum.MapForumNodeToModel(IPublishedContent forumRoot) +0
   nForum.BusinessLogic.Models.Forum..ctor(Nullable`1 overideNodeId) +141
   nForum.BusinessLogic.Helpers.MainForumSettings(Nullable`1 overideRoot) +212
   nForum.BusinessLogic.BaseForumUsercontrol.get_Settings() +77
   nForum.usercontrols.nForum.membership.Register.BtnSubmitClick(Object sender, EventArgs e) +84
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +155
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804

Can any help me please?

**Comment by YodasMyDad** [comment]
This is nForum not dialogue
