### ISSUE TITLE
error when installing dialogue 1.1

### ISSUE THREAD

**Issue by sy8718** [YodasMyDad/Dialogue#66]
Hi all

I tried to install dialogue 1.1 on my umbraco and it throw an error

A route named "umbraco-surface-BaseSurface" is already in the route collection. Route names must be unique. Parameter name: name

Then I have to roll back my bin folder to make it work again.

Anyone has any idea?

Thanks

**Comment by YodasMyDad** [comment]
Looks like you already have a route with the same alias.
