### ISSUE TITLE
CS0234 Exception, Microsoft.Web.Helpers not found

### ISSUE THREAD

**Issue by charleslbryant** [YodasMyDad/Dialogue#77]
I installed Umbraco from NuGet package. Then installed Dialogue from the package repository in the Back Office. After I publish the forum page and categories, I get an exceptions when attempting to open the forum:

Compilation Error

Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS0234: The type or namespace name 'Helpers' does not exist in the namespace 'Microsoft.Web' (are you missing an assembly reference?)

Source Error:

Line 29:     using Umbraco.Core.Models;
Line 30:     using Umbraco.Web.Mvc;
Line 31:     using Microsoft.Web.Helpers;
Line 32:     using umbraco;
Line 33:     using Examine;

**Comment by charleslbryant** [comment]
I found that the Microsofte.Web.Helpers namespace is included in the View web.config at \App_Plugins\Dialogue\Themes\Default\Views\Web.Config. I fixed the issue by updating 

<namespaces>
        <add namespace="Microsoft.Web.Helpers" />

To

<namespaces>
        <add namespace="System.Web.Helpers" />

**Comment by YodasMyDad** [comment]
Thanks, will amend in next version
