### ISSUE TITLE
Preventing an version upgrade from Umbraco 7.1.4 to 7.5.3

### ISSUE THREAD

**Issue by RachBreeze** [YodasMyDad/Dialogue#80]
We have a live Umbraco 7.1.4  website that uses Dialogue .

I am trying to upgrade it to Umbraco 7.5.3.  However I'm getting the error Invalid column name 'uniqueID'.

This is raised in Dialogue.Logic.Events.UmbracoEvents.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +114

This is because it's iterating over published content before the upgrade to add the uniqueID column has been completed.  

See http://issues.umbraco.org/issue/U4-7100#comment=67-28151.

**Comment by YodasMyDad** [comment]
I would comment that out and go to /umbraco/ and do the upgrade, then uncomment it once the install is done. Unfortunately with all the best intentions in the world, I just haven't got the time to update this project at the moment :(

**Comment by RachBreeze** [comment]
Thank you

**Comment by YodasMyDad** [comment]
Strangely, I have just re-read that thread and Seb is saying to make sure the code is in the ApplicationEventHandler? Which is exactly where it is in Dialogue... Also, this is identical code that Articulate uses?

https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/UmbracoEventHandler.cs#L47

I haven't heard anyone else having an upgrade issue. Are you 100% certain is was this code stopping you upgrade?

**Comment by YodasMyDad** [comment]
So, this was either an issue with an earlier version of Umbraco/Dialogue. I have just updated the project to the latest version of Umbraco without an issue. So will close this for now.
