### ISSUE TITLE
Package.manifest reference files that are not present (2.0)

### ISSUE THREAD

**Issue by JohnBergman** [YodasMyDad/Dialogue#88]
It appears that there are missing files.

In the project.manifest there is this:

    	    '~/App_Plugins/Dialogue/backoffice/dialoguetree/controllers/view.controller.js',
		'~/App_Plugins/Dialogue/backoffice/dialoguetree/controllers/edit.controller.js',
		'~/App_Plugins/Dialogue/backoffice/dialoguetree/controllers/overview.controller.js',
		'~/App_Plugins/Dialogue/backoffice/dialoguetree/controllers/bannedemail.controller.js',
		'~/App_Plugins/Dialogue/backoffice/dialoguetree/controllers/bannedword.controller.js',
		'~/App_Plugins/Dialogue/backoffice/dialoguetree/resources/bannedemail.resource.js',

But those files are no where to be found

**Comment by YodasMyDad** [comment]
Those are not needed. I'll remove them from the manifest
