### ISSUE TITLE
2.0 Distribution missing CssPicker and PartialPicker implementation

### ISSUE THREAD

**Issue by JohnBergman** [YodasMyDad/Dialogue#89]
The data types are installed for "Partial Picker" and "Css Picker", but when you click on them you get an error about "Apt.CssPicker" or "Apt.PartialPicker".

This can be seen from Developer -> Data Types -> Css Picker 
and  Developer -> Data Types -> Partial Picker
--
System.InvalidOperationException: Could not find property editor with alias Apt.PartialPicker

**Comment by YodasMyDad** [comment]
Ok thanks. Will check the package installer.

**Comment by YodasMyDad** [comment]
They are now definitely added to the package
