### ISSUE TITLE
Crash when no Document in content Tree

### ISSUE THREAD

**Issue by JohnBergman** [YodasMyDad/Dialogue#92]
If you should happen to delete the main document node, you are unable to recreate one because of exceptions being thrown.

This originates within the dialogue.cs file within the Settings() method.

var currentPage = AppHelpers.CurrentPage()

If there are no documents, this is null, and the next call to try to retrieve the DialogDocument fails with a null pointer exception.

Q: Is it ok to simply return a DialogueSettings object that has not had any of the information added to it?

**Comment by JohnBergman** [comment]
Just guarding the null and returning like the last line of the method does at least allows the site to continue running.

Looking closer at this, it seems like ServiceResolver.cs's Instance<TService> method should create the object, and the initialize it as a separate call.  This would at least provide an error that makes more sense that "object must have an empty constructor" message you see now.

Further, once this exception happens, many of the other controls fail to work because the initialization code never completes, IMHO, the implementation should guard against destabilizing the whole site somehow.

**Comment by YodasMyDad** [comment]
Will look into
