### ISSUE TITLE
Error banner displayed after confirming email

### ISSUE THREAD

**Issue by cmdigital** [YodasMyDad/Dialogue#94]
I am using forum version 2.0 beta.

When new members are sent an email to confirm their identity and activate their forum membership everything appears to work but a red banner with "There was an error" appears in the top of the page.

The membership is activated but the error message will confuse users.

**Comment by cmdigital** [comment]
Looking into the code found that in the DialoguePageController, EmailConfirmation class the last line return ErrorToHomePage(Lang("Errors.GenericMessage")); 

gets executed even if there are no issues, thus generating the banner.

It should be a fairly easy fix.

**Comment by YodasMyDad** [comment]
Thanks.
